language: java
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_b91d715816e9_key -iv $encrypted_b91d715816e9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- chmod +x gradlew
- ./gradlew mbGenerator
script:
- ./gradlew build
addons:
  ssh_known_hosts: 39.108.158.105
after_success:
- scp ./build/libs/librarian-1.0-SNAPSHOT.jar root@39.108.158.105:/root/librarian
- ssh root@39.108.158.105 "~/librarian/librarian_deploy.sh"
