server:
  address: 0.0.0.0
  port: 7799

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_ms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#pagehelper分页插件
#pagehelper:
    #helperDialect: mysql
    #reasonable: true
    #supportMethodsArguments: true
    #params: count=countSql
