server:
  address: 0.0.0.0
  port: 7799

spring:
  datasource:
    url: jdbc:mysql://39.108.158.105:3306/librarian?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: enok
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
