server:
  address: 0.0.0.0
  port: 7799

spring:
  datasource:
    url: jdbc:mysql://39.108.158.105:3306/librarian?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: enok
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: LOWER_CASE

jedis :
  pool :
    host : 127.0.0.1
    port : 6379
    password: Eyee3111
    database: 0
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000

# JWT
jwt:
  header: Authorization
  secret: KKKsewen77Enok
  expiration: 604800
  tokenHead: "Rabbit "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
logging:
  level:
    com.enokb.librarian: debug
  file: log/librarian.log
  path: log/

# log
